config/routes.rb
Rails.application.routes.draw do


devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
root to: 'location#index'

 devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end

  resources :location do
    member do
    get 'preload'
    get 'preview'
  end
    resources :reviews, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :photos, only: [:create, :destroy]
  end

  get '/your_trips' => 'reservations#your_trips'
  get 'search' => 'location#search'

  # --------- DashBoard --------
  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do 
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  get '/payment_method' => 'users#payment'
  post '/add_card' => "users#add_card"
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" style ="margin-bottom: 0px">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <%= link_to "Lowkey", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
          </div>
      <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if (!user_signed_in?) %>
              <li><%=link_to "Login", new_user_session_path %></li>
               <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% else %>
            <li>
                <button class="btn btn-form btn-small">
                  <%= link_to "Dashboard", dashboard_path , style: "color: white; text-decoration: none;" %>
                </button>
              </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
                  role="button" aria-haspopup="true" aria-expanded="false"> 
                  <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
                  <%= current_user.fullname %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#">Manage Payment</a></li>
                <li><a href="#">List Favorite Spaces</a></li>
                <li><a href="/your_trips">Your Trips</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  
    <% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/location/#{params[:id]}")&& !current_page?(search_path)%>
       <nav class="navbar navbar-default" style="background-color: #565A5C">
          <div class="container">
            <ul class="nav navbar-nav">
            <li <% if current_page?(dashboard_path) %> class="active" <% end %> >
            <%= link_to "Dashboard", dashboard_path %>
            <li <% if current_page?(payment_method_path) %> class="active" <% end %> ><%= link_to "Account Settings", payment_method_path %></li>
            </li>
          </ul>
      </div>
    </nav>
<% end %>