config/routes.rb
Rails.application.routes.draw do


devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
root to: 'location#index'

 devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end

  resources :location do
    member do
    get 'preload'
    get 'preview'
  end
    resources :reviews, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :photos, only: [:create, :destroy]
  end

  get '/your_trips' => 'reservations#your_trips'
  get 'search' => 'location#search'

  # --------- DashBoard --------
  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do 
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end

  get '/payment_method' => 'users#payment'
  post '/add_card' => "users#add_card"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  enum status: {Waiting: 0, Approved: 1, Declined: 2}

  belongs_to :user
  belongs_to :location
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:approve, :decline]

  def create
    location = Location.find(params[:location_id])

    if current_user.stripe_id.blank?
      flash[:alert] = "Please update your payment method."
      return redirect_to payment_method_path
    else

    start_time = Time.parse(reservation_params[:start_time])
    end_time = Time.parse(reservation_params[:end_time])
    times = (end_time.hour - start_time.hour).to_i

    @reservation = current_user.reservations.build(reservation_params)
    @reservation.location = location
    @reservation.price = location.price
    @reservation.total = location.price * times
    # @reservation.save

    if @reservation.Waiting!
        if location.Request?
          flash[:notice] = "Request sent successfully!"
        elsif @reservation.Approved!
          charge(location, @reservation)
        end
      else
        flash[:alert] = "Cannot make a reservation!"
      end

    end
    redirect_to location
  end

  def your_trips
    @trips = current_user.reservations.order(id: :desc)
  end

  def approve
    charge(@reservation.location, @reservation)
    redirect_to your_reservations_path 
  end

  def decline
    @reservation.Declined!
    redirect_to your_reservations_path
  end

  private

 def charge(location, reservation)
      if !reservation.user.stripe_id.blank?
        customer = Stripe::Customer.retrieve(reservation.user.stripe_id)
        charge = Stripe::Charge.create(
          :customer => customer.id,
          :amount => reservation.total * 100,
          :description => location.lisiting_name,
          :currency => "usd",
        )

        if charge
          reservation.Approved!
          flash[:notice] = "Reservation created successfully!"
        else
          reservation.Declined!
          flash[:alert] = "Cannot charge with this payment method!"
        end
      end
    rescue Stripe::CardError => e
      reservation.Declined!
      flash[:alert] = e.message
    end

   def send_sms(location, reservation)
      @client = Twilio::REST::Client.new
      @client.messages.create(
        from: '+61437798403',
        to: self.phone_number,
        body: "Hi #{reservation.user.fullname}! you have been approved with a booking reservation from '#{start_time} to '#{end_time} at '#{location.listing_name}'"
      )
    end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

    def reservation_params
      params.require(:reservation).permit(:start_time, :end_time)
    end
end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
     <span><% if @location.Instant? %><i class="fa fa-bolt" style="color: #ffb400"></i> <% end %> $<%= @location.price %></span>
    <span class="pull-right">Per Hour</span>
  </div>
  <div class="panel-body">
 <%= form_for([@location, @location.reservations.new]) do |f| %>
   <div class="row">
      <div class="col-md-6">
          <label>Start Time</label>
              <%= f.text_field :start_time, readonly: true, placeholder: "Start Time", class: "form-control
               timepicker"%>
          </div>
              <div class="col-md-6">
                <label>End Time</label>
              <%= f.text_field :end_time, readonly: true, placeholder: "End Time", class: "form-control timepicker"  %>
              </div>
           </div>

    <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>Price</td>
              <td class="text-right">$<%= @location.price %></td>
            </tr>
            <tr>
              <td>Hour(s)</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">Total</td>
              <td class="text-right">$<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>
      <% if @location.Instant? %>
          <%= f.submit "Book Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: false %>
      <% else %>
          <%= f.submit "Request Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: false %>
      <% end %>
    <% end %>
  </div>
</div>

 <script> 
 $(function() {
  $('#reservation_start_time').timepicker({
    timeFormat: 'h:mm p',
    interval: 60,
    minTime: '10',
    maxTime: '10:00pm',
    defaultTime: '11',
    startTime: '10:00',
    dynamic: true,
    dropdown: true,
    scrollbar: true
  });
  $('#reservation_end_time').timepicker({
    timeFormat: 'h:mm p',
    interval: 60,
    minTime: '10',
    maxTime: '10:00pm',
    defaultTime: '11',
    startTime: '10:00',
    dynamic: true,
    dropdown: true,
    scrollbar: true
   });
  });
 </script>

app/views/reservations/your_trips.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
    <li class="sidebar-item"><%= link_to "View My Profile", user_path(current_user.id), class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Trips
      </div>
      <div class="panel-body">

        <% @trips.each do |trip| %>
          <div class="row">
          <div class="col-md-3">
              <%= trip.start_time.strftime('%v') %>
              <p><%= trip.status %></p>
            </div>
            <div class="col-md-3">
              <%= link_to location_path(trip.location) do %>
                <%= image_tag trip.location.image(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= link_to trip.location.lisiting_name, location_path(trip.location) %><br/><br/>
              </div>
              <div class="col-md-3">
              <span>
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %>
              </span>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>